vich_uploader:
    db_driver: orm

    metadata:
        type: users
    mappings:
       users:
           uri_prefix: /images/users
           upload_destination: '%kernel.project_dir%/public/images/users'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       voitures:
           uri_prefix: /images/videos
           upload_destination: '%kernel.project_dir%/public/images/videos'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer